
# This file is used to configure your Supabase Functions.
# When fetching credentials and environment variables, please refer to this guide:
# https://supabase.com/docs/guides/functions/secrets

project_id = "ijrnwpgsqsxzqdemtknz"

[functions.updateKPIs]
verify_jwt = true

[functions.syncMQLs]
verify_jwt = true

[functions.autoEvolveAgents]
verify_jwt = true

[functions.createDbFunctions]
verify_jwt = true
