
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ref.
project_id = "ijrnwpgsqsxzqdemtknz"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure a session pool (transaction) or a statement pool (statement)
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

[auth.external.apple]
enabled = false
# Client ID for the Apple provider.
client_id = ""
# Secret for the Apple provider.
secret = ""
# Authorize URI for the Apple provider.
authorize_uri = "https://appleid.apple.com/auth/authorize"
# Token URI for the Apple provider.
token_uri = "https://appleid.apple.com/auth/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Apple provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://appleid.apple.com/auth/authorize?response_type=code&response_mode=form_post"
# Auth URL for the Apple provider.
# This is used for the `add_auth_params` to obtain user authorization and authentication.
authUrl = "https://appleid.apple.com/auth/authorize?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&scope=name%20email&response_type=code%20id_token&response_mode=form_post"

[auth.external.azure]
enabled = false
# Client ID for the Azure provider.
client_id = ""
# Secret for the Azure provider.
secret = ""
# Authorize URI for the Azure provider.
authorize_uri = "https://login.microsoftonline.com/tenant-id/oauth2/v2.0/authorize"
# Token URI for the Azure provider.
token_uri = "https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Azure provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://login.microsoftonline.com/tenant-id/oauth2/v2.0/authorize?response_type=code"

[auth.external.bitbucket]
enabled = false
# Client ID for the Bitbucket provider.
client_id = ""
# Secret for the Bitbucket provider.
secret = ""
# Authorize URI for the Bitbucket provider.
authorize_uri = "https://bitbucket.org/site/oauth2/authorize"
# Token URI for the Bitbucket provider.
token_uri = "https://bitbucket.org/site/oauth2/access_token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Bitbucket provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://bitbucket.org/site/oauth2/authorize?response_type=code"

[auth.external.discord]
enabled = false
# Client ID for the Discord provider.
client_id = ""
# Secret for the Discord provider.
secret = ""
# Authorize URI for the Discord provider.
authorize_uri = "https://discord.com/api/oauth2/authorize"
# Token URI for the Discord provider.
token_uri = "https://discord.com/api/oauth2/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Discord provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://discord.com/api/oauth2/authorize?response_type=code"

[auth.external.facebook]
enabled = false
# Client ID for the Facebook provider.
client_id = ""
# Secret for the Facebook provider.
secret = ""
# Authorize URI for the Facebook provider.
authorize_uri = "https://facebook.com/v17.0/dialog/oauth"
# Token URI for the Facebook provider.
token_uri = "https://graph.facebook.com/v17.0/oauth/access_token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Facebook provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://facebook.com/v17.0/dialog/oauth?response_type=code"

[auth.external.figma]
enabled = false
# Client ID for the Figma provider.
client_id = ""
# Secret for the Figma provider.
secret = ""
# Authorize URI for the Figma provider.
authorize_uri = "https://www.figma.com/oauth"
# Token URI for the Figma provider.
token_uri = "https://www.figma.com/api/oauth/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Figma provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://www.figma.com/oauth?response_type=code"

[auth.external.github]
enabled = false
# Client ID for the GitHub provider.
client_id = ""
# Secret for the GitHub provider.
secret = ""
# Authorize URI for the GitHub provider.
authorize_uri = "https://github.com/login/oauth/authorize"
# Token URI for the GitHub provider.
token_uri = "https://github.com/login/oauth/access_token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the GitHub provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://github.com/login/oauth/authorize?response_type=code"

[auth.external.gitlab]
enabled = false
# Client ID for the GitLab provider.
client_id = ""
# Secret for the GitLab provider.
secret = ""
# Authorize URI for the GitLab provider.
authorize_uri = "https://gitlab.com/oauth/authorize"
# Token URI for the GitLab provider.
token_uri = "https://gitlab.com/oauth/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the GitLab provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://gitlab.com/oauth/authorize?response_type=code"

[auth.external.google]
enabled = false
# Client ID for the Google provider.
client_id = ""
# Secret for the Google provider.
secret = ""
# Authorize URI for the Google provider.
authorize_uri = "https://accounts.google.com/o/oauth2/auth"
# Token URI for the Google provider.
token_uri = "https://oauth2.googleapis.com/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Google provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://accounts.google.com/o/oauth2/auth?response_type=code"

[auth.external.kakao]
enabled = false
# Client ID for the Kakao provider.
client_id = ""
# Secret for the Kakao provider.
secret = ""
# Authorize URI for the Kakao provider.
authorize_uri = "https://kauth.kakao.com/oauth/authorize"
# Token URI for the Kakao provider.
token_uri = "https://kauth.kakao.com/oauth/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Kakao provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://kauth.kakao.com/oauth/authorize?response_type=code"

[auth.external.keycloak]
enabled = false
# Client ID for the Keycloak provider.
client_id = ""
# Secret for the Keycloak provider.
secret = ""
# Authorize URI for the Keycloak provider.
authorize_uri = ""
# Token URI for the Keycloak provider.
token_uri = ""
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Keycloak provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = ""

[auth.external.linkedin]
enabled = false
# Client ID for the LinkedIn provider.
client_id = ""
# Secret for the LinkedIn provider.
secret = ""
# Authorize URI for the LinkedIn provider.
authorize_uri = "https://www.linkedin.com/oauth/v2/authorization"
# Token URI for the LinkedIn provider.
token_uri = "https://www.linkedin.com/oauth/v2/accessToken"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the LinkedIn provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://www.linkedin.com/oauth/v2/authorization?response_type=code"

[auth.external.notion]
enabled = false
# Client ID for the Notion provider.
client_id = ""
# Secret for the Notion provider.
secret = ""
# Authorize URI for the Notion provider.
authorize_uri = "https://api.notion.com/v1/oauth/authorize"
# Token URI for the Notion provider.
token_uri = "https://api.notion.com/v1/oauth/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Notion provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://api.notion.com/v1/oauth/authorize?response_type=code"

[auth.external.spotify]
enabled = false
# Client ID for the Spotify provider.
client_id = ""
# Secret for the Spotify provider.
secret = ""
# Authorize URI for the Spotify provider.
authorize_uri = "https://accounts.spotify.com/authorize"
# Token URI for the Spotify provider.
token_uri = "https://accounts.spotify.com/api/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Spotify provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://accounts.spotify.com/authorize?response_type=code"

[auth.external.slack]
enabled = false
# Client ID for the Slack provider.
client_id = ""
# Secret for the Slack provider.
secret = ""
# Authorize URI for the Slack provider.
authorize_uri = "https://slack.com/oauth/authorize"
# Token URI for the Slack provider.
token_uri = "https://slack.com/api/oauth.access"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Slack provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://slack.com/oauth/authorize?response_type=code"

[auth.external.twitch]
enabled = false
# Client ID for the Twitch provider.
client_id = ""
# Secret for the Twitch provider.
secret = ""
# Authorize URI for the Twitch provider.
authorize_uri = "https://id.twitch.tv/oauth2/authorize"
# Token URI for the Twitch provider.
token_uri = "https://id.twitch.tv/oauth2/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Twitch provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://id.twitch.tv/oauth2/authorize?response_type=code"

[auth.external.twitter]
enabled = false
# Client ID for the Twitter provider.
client_id = ""
# Secret for the Twitter provider.
secret = ""
# Authorize URI for the Twitter provider.
authorize_uri = "https://twitter.com/i/oauth2/authorize"
# Token URI for the Twitter provider.
token_uri = "https://api.twitter.com/2/oauth2/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Twitter provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://twitter.com/i/oauth2/authorize?response_type=code"

[auth.external.workos]
enabled = false
# Client ID for the WorkOS provider.
client_id = ""
# Secret for the WorkOS provider.
secret = ""
# Authorize URI for the WorkOS provider.
authorize_uri = "https://api.workos.com/sso/authorize"
# Token URI for the WorkOS provider.
token_uri = "https://api.workos.com/sso/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the WorkOS provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://api.workos.com/sso/authorize?response_type=code"

[auth.external.zoom]
enabled = false
# Client ID for the Zoom provider.
client_id = ""
# Secret for the Zoom provider.
secret = ""
# Authorize URI for the Zoom provider.
authorize_uri = "https://zoom.us/oauth/authorize"
# Token URI for the Zoom provider.
token_uri = "https://zoom.us/oauth/token"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# URI for the Zoom provider to improve the sign in experience.
# This is used for the `add_auth_params` to improve the user experience.
url = "https://zoom.us/oauth/authorize?response_type=code"

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of these backends
backend = "postgres"

# Postgres backend for Analytics
[analytics.postgres]
# Where to store the analytics data
db_url = "postgres://postgres:postgres@localhost:54322/postgres"
# The table to store the analytics events
track_table = "analytics.track"
# When true, will automatically create the table
auto_create_table = true

[experimental.functions]
[functions.executeStrategy]
verify_jwt = true
[functions.syncHubSpotMQLs]
verify_jwt = true
[functions.syncMQLs]
verify_jwt = true
[functions.updateKPIs]
verify_jwt = true
[functions.send-invite-email]
verify_jwt = true
[functions.sendMilestoneAlerts]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
