
project_id = "ijrnwpgsqsxzqdemtknz"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[edge_functions.generateStrategy]
verify_jwt = true

[edge_functions.analyzePromptDiff]
verify_jwt = true
