
project_id = "ijrnwpgsqsxzqdemtknz"

[auth]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions]
enabled = true

[functions.executeStrategy]
verify_jwt = true

[functions.send-invite-email]
verify_jwt = true

[functions.syncMQLs]
verify_jwt = true
schedule = "0 0 * * *"  # Run daily at midnight

[functions.updateKPIs]
verify_jwt = true
schedule = "0 */6 * * *"  # Run every 6 hours
