
project_id = "ijrnwpgsqsxzqdemtknz"

[functions.updateKPIs]
verify_jwt = true

[functions.syncMQLs]
verify_jwt = true

[functions.autoEvolveAgents]
verify_jwt = true

[functions.executeStrategy]
verify_jwt = true

[functions.createDbFunctions]
verify_jwt = true
