
project_id = "ijrnwpgsqsxzqdemtknz"

[api]
enabled = true

[db]
shadow_database_url = ""

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "https://allora-workspace.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
[edge_functions.executeStrategy]
verify_jwt = true

[edge_functions.send-webhook-alert]
verify_jwt = true

[edge_functions.send-invite-email]
verify_jwt = true

[edge_functions.sendMilestoneAlerts]
verify_jwt = true

[edge_functions.syncMQLs]
verify_jwt = true

[edge_functions.updateKPIs]
verify_jwt = true

[edge_functions.syncHubSpotMQLs]
verify_jwt = true
