
import { Strategy } from '@/types/strategy';

// Mock strategies for development and testing
export const mockStrategies: Strategy[] = [
  {
    id: '1',
    title: 'Content Marketing Campaign',
    description: 'Create a comprehensive content marketing strategy for Q3',
    status: 'approved',
    created_by: 'user1',
    created_at: '2023-06-15T10:00:00Z',
    updated_at: '2023-06-16T14:30:00Z',
    approved_by: 'admin1',
    approved_at: '2023-06-16T14:30:00Z',
    rejected_by: null,
    rejected_at: null,
    tenant_id: 'tenant1',
    priority: 'high',
    tags: ['content', 'marketing', 'Q3'],
    due_date: '2023-09-30T00:00:00Z',
    completion_percentage: 35,
    metadata: { goals: ['increase traffic', 'generate leads'] }
  },
  {
    id: '2',
    title: 'Website Redesign',
    description: 'Redesign the company website with new branding',
    status: 'pending',
    created_by: 'user2',
    created_at: '2023-06-10T08:15:00Z',
    updated_at: '2023-06-10T08:15:00Z',
    approved_by: null,
    approved_at: null,
    rejected_by: null,
    rejected_at: null,
    tenant_id: 'tenant1',
    priority: 'medium',
    tags: ['website', 'redesign', 'branding'],
    due_date: '2023-08-15T00:00:00Z',
    completion_percentage: 0,
    metadata: { stakeholders: ['marketing', 'sales'] }
  },
  {
    id: '3',
    title: 'Email Drip Campaign',
    description: 'Set up automated email drip campaign for new leads',
    status: 'in_progress',
    created_by: 'user1',
    created_at: '2023-05-20T16:45:00Z',
    updated_at: '2023-06-02T11:20:00Z',
    approved_by: 'admin1',
    approved_at: '2023-05-22T09:30:00Z',
    rejected_by: null,
    rejected_at: null,
    tenant_id: 'tenant1',
    priority: 'low',
    tags: ['email', 'automation', 'leads'],
    due_date: '2023-07-01T00:00:00Z',
    completion_percentage: 65,
    metadata: { platform: 'MailChimp', segments: ['new leads', 'cold leads'] }
  },
  {
    id: '4',
    title: 'PPC Campaign Optimization',
    description: 'Optimize Google Ads and Facebook campaigns for better ROI',
    status: 'rejected',
    created_by: 'user3',
    created_at: '2023-06-05T13:10:00Z',
    updated_at: '2023-06-07T15:30:00Z',
    approved_by: null,
    approved_at: null,
    rejected_by: 'admin2',
    rejected_at: '2023-06-07T15:30:00Z',
    tenant_id: 'tenant1',
    priority: 'high',
    tags: ['ppc', 'ads', 'optimization'],
    due_date: '2023-06-30T00:00:00Z',
    completion_percentage: 0,
    metadata: { reason: 'Budget constraints', platforms: ['Google Ads', 'Facebook'] }
  },
  {
    id: '5',
    title: 'Social Media Content Calendar',
    description: 'Develop a 3-month content calendar for all social channels',
    status: 'completed',
    created_by: 'user2',
    created_at: '2023-04-10T09:20:00Z',
    updated_at: '2023-05-15T16:45:00Z',
    approved_by: 'admin1',
    approved_at: '2023-04-11T10:00:00Z',
    rejected_by: null,
    rejected_at: null,
    tenant_id: 'tenant1',
    priority: 'medium',
    tags: ['social media', 'content', 'planning'],
    due_date: '2023-05-15T00:00:00Z',
    completion_percentage: 100,
    metadata: { channels: ['Instagram', 'Twitter', 'LinkedIn', 'Facebook'] }
  }
];

export default mockStrategies;
